import { root } from 'postcss';
import { Dashboard } from '../components/layout/Dashboard.js';
import { Geist, Geist_Mono } from "next/font/google";
import './styles/globals.css';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <html lang="en">
      <body>
        <Dashboard />
      </body >
    </html >
  )
}

